apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-calls-service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api-calls-service-b
  template:
    metadata:
      labels:
        app: python-api-calls-service-b
    spec:
      containers:
        - name: python-api-calls-service-b
          image: fredwinrosales/python-api-calls-service-b:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              ephemeral-storage: "100Mi"
            limits:
              ephemeral-storage: "200Mi"
          imagePullPolicy: Always
