apiVersion: v1
kind: Service
metadata:
  name: python-api-calls-service-b-service
spec:
  selector:
    app: python-api-calls-service-b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
